{% set name = "jobflow" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jobflow-{{ version }}.tar.gz
  sha256: 8121fcd4c4fc42240a8e0e9808b6aa67ead887645334bac37cd3881a9b57fda0
  patches:
    - version.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - maggma >=0.38.1
    - monty >=2021.5.9
    - networkx
    - pydantic
    - pydash
    - python >={{ python_min }}
    - pyyaml
    - setuptools

test:
  imports:
    - jobflow
    - jobflow.core
  commands:
    - pip check
    - pip list | grep jobflow
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://materialsproject.github.io/jobflow
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: jobflow is a library for writing computational workflows.
  description: |
    Jobflow is a free, open-source library for writing and executing
    workflows. Complex workflows can be defined using simple python
    functions and executed locally or on arbitrary computing resources
    using the FireWorks workflow manager.
  doc_url: https://materialsproject.github.io/jobflow
  dev_url: https://github.com/materialsproject/jobflow

extra:
  recipe-maintainers:
    - jan-janssen
